version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: conferenceServise
    ports:
      - "5432:5432"
    volumes:
      - E:\DataBase\postgresqlDataDocker:/var/lib/postgresql/data

  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"

  web:
    image: cfapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=conferenceServise;Username=postgres;Password=0000"
    ports:
      - "8080:80"
    depends_on:
      - db

